version = 0.1
[y.deploy.parameters]
stack_name = "lambda-s3-envt-trigger"
resolve_s3 = true
s3_prefix = "lambda-s3-envt-trigger"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
