AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Process Uploaded Log Files in S3 Bucket Using AWS Lambda Triggered by EventBridge


Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./lambda_function/app.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_function
      MemorySize: 128
      Timeout: 30
      Architectures:
      - x86_64
    Tags:
      Name: MyLambdaFunction

Outputs:
  LambdaFunctionArn:
    Value: !GetAtt [MyFunction, Arn]
    Export:
      Name: LambdaFunctionArn